#!/bin/sh

set -e

cp /usr/share/starlingx/openldap/initscript /etc/init.d/openldap
cp /usr/share/starlingx/openldap/slapd.conf /etc/ldap/slapd.conf
cp /usr/share/starlingx/openldap/initial_config.ldif /etc/ldap/initial_config.ldif
cp /usr/share/starlingx/openldap/slapd.syslog-ng.conf /etc/syslog-ng/conf.d/slapd.conf
cp /usr/share/starlingx/openldap/slapd.logrotate /etc/logrotate.d
cp /usr/share/starlingx/openldap/slapd.sysconfig /etc/default/slapd

chmod 755 /etc/init.d/slapd
chmod 740 /etc/ldap/
chmod 600 /etc/ldap/slapd.conf
chmod 600 /etc/ldap/initial_config.ldif
chmod 644 /etc/syslog-ng/conf.d/slapd.conf
chmod 644 /etc/logrotate.d/slapd.logrotate
chmod 644 /etc/systemd/system/slapd.service
chmod 644 /etc/default/slapd

# Remove 'ldap' from sudoers nsswitch line injected by sudo-ldap postinst.
# STX uses SSSD ('sss') for sudo rule lookups from LDAP, not the sudo-ldap
# direct LDAP client. The direct 'ldap' entry is redundant and causes a
# 3-second connection timeout on every sudo call when slapd is not running
# (e.g. during restore and early unlock).
sed -i 's/^sudoers:.*/sudoers: files sss/' /etc/nsswitch.conf

#DEBHELPER#
