---
- project:
    check:
      jobs:
        - openstack-tox-linters
    gate:
      jobs:
        - openstack-tox-linters
    post:
      jobs:
        - stx-config-files-upload-git-mirror

- job:
    name: stx-config-files-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/config-files to
      github.com/starlingx/config-files
    vars:
      git_mirror_repository: starlingx/config-files
    secrets:
      - name: git_mirror_credentials
        secret: stx-config-files-github-secret3
        pass-to-parent: true

- secret:
    name: stx-config-files-github-secret3
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - H3c2vbG+fHxJAfkQ+kU61PH+EbHuprzvgU3tmbYU5GMJqY1PzoceDb41FAg4Tj6m9Dtn9
          umrnuMXL2iLXIeIgrWrCoEOjFeyILO7ArDFtorjXphLXNT9Wn40RkoUDYTb3xYJYMx4Yr
          B0K9ZJ6Bsi3NgRDiRXy6DwqtMMTx1yxOM6RktmKb/dkc40XwUUrS8AM6I/Qu1jWf893Uj
          OHt13g3qBUXn3TU10QWv2ox6Z3n7Nahx3e5jHidcfH1Tzv+aHZZU1MUBxo+LIAPKPuyab
          lDu7Ll4oa1M8o5oUibgJl2RhOdcWitRkWkt50JKPAgxg1pWDrhfTdKUKSafmlQHcgV+Yi
          G4Bbpvv/5G1I6b8v+zC+G7PviyYjtgU6dvux/7fkmlNU+qCf4RRcFFjcu5SI0Tz/u7aIQ
          RMXmVCmLMssB3Zfd84RKtLQihnOJjiZnQOV5igCXpqpp+9PPzy5qwzK4Lz+yC/DR6Slvp
          glK9yAI7bcTXrQzr7lMMRROhJ2NOB9HScWulG/VirNrxzgmI2PZa7vqigssfMwMkLAkxD
          GF7ilimOZ8pHLUQqGP94jeHqho8SV6ioPIiUjMoZTNGMuM8CRWI3CtTNRUr3hc8g4h/pt
          4/40i4iiEChC5UIDdA6jUO1OGIW485GJB/0CeqMb/H5EfhJ5F8inAf1NWWWhZ8=
        - hthkFtHQlZQ9HscqhfcO6JPSq77VcYiG891iQUC+Rsn0NVi6KRqpxPaaDYDyxR1CO2ac/
          Y2I5dBhWK7Pwk1bOXWB45ooqzpJJJoytdki5D7rz+4kV3A8IVYKDcuZ5raI3dxEZotMGn
          BLivbNluXcDkKZRpmUdBA7Z14xLo8ozBAbT0QsHebjW304m4vB6DC5GKU1HYXCNTISsB2
          /3Bd4dTbZo8Ge/O+MOHNHV9gHjZAcTzvw8iz48omDnqGMQzWChtvV4eN5Y8tKwQD1tWl5
          dRZSWuXpifYU0OsD8rGorwVV26EvTjLh6sdng/m6/qbGIM07juOftL66WZqBHlOxpxrD7
          lFcqeccjmMM0Bk0YuI5YvknJSU8TYE8/0WmD7YB7MFLFx9dcmPBVhsRx9TH3Rc9PI1ita
          vvsT05pa0FYbdv8f76RUGZtv2BIcfq4Umb4fViNYtjqGgR5wh8Pf6LwFgaBRr0M8GJK+g
          KF2kkMKH7ACm3DOfqT9QXGsc/O6BEZWtb4RIaqbZQJq/WYATjCUAeYCvMUcqpDsIiRBHZ
          5kuv/0UdzeVREZZHjeX7YKESOaYa92K41Ea3ZfvdcA2GuFasNERwyS6TK6VjuQDlTmaw+
          0KlxjF7rQ9j2rEQ0MBiSUVFvI2zJ7vLjYg3hyskZIa73RUJyMsKmV02qY/Pf80=
        - R0NT4xgDD2AfNiE07hDNeYyX0sPlkqRDbIm7rFiQ61nzc9az3YyGTBNxXPkv+HUkQtl3H
          v3xmST9AIKxwmAJChtkGyzRPaHydxciO8ruLyDPHKOf1Q2y7UfOJ70Yj73x4JG7XMcO4E
          S7oOJI3v3W+9iV+I6zBoVYSRcNalEH1PaIlTzFOpU3jhvBZ71CNVjP8io6B1TSTMcCT12
          UADzptSuj5NXwLXmS4ysvePDGSHOS+PhFSH36lO+U7p/PO+ySVSE2wTScb/N023eQFUk+
          vOlEm3cVt/COVCIeuonJA+GeOieEqUR0Z1IQgq1oc315VPADMTR5Lt+8x+wqyL/jZWSD5
          vlrXq/AlyIXo//i+WPpV1bW+u7be7L29akOQxt/1DLESPwvoFYoCYTXix64oWMRmBtesm
          oxvAwGP2zKeI6lfu7f5YTLc8rs4ffC3VFUQsC1ra5RTL3lvC6qSHsaANCKpgrAz90EWGo
          z/dq9CxgKrAfkP9s0swjsFg9brPOz/68HqnZowGyqOicIY+r7tbdn9W/AbIKyEUjxlFAG
          mc/vP6VzIC0i/e9/P86RRB3qAcKzIn0wuEvuzrEA7zT8OFTir59hwjQUvruZtXmg9v316
          MTIr4JCBhtZx1DBklHGRRukQWFYMN8S/Pu1alAK0vbBRtW+fap9+M9XTW1/YVA=
        - EprMTzteyG3/Lh2eouI/BGu+lrOEM7UNHeZnwmnSXFw1Lhvt5sdfbah9C+Nzs5UpSJ1Kk
          RtkMZcJckvcxW3Nd28zhoxumAHG7rGRCYtYdfLEr9XfX9iXP2L3OTSjIMY43mR+NecYpm
          5ZWeKFDvrqq603iPGSOYrNCQP/ZaoW27gp7lgh7Lvscztv5Lt4wA0uMP4ExgK3ojITffy
          XARZfI8iEimLzKepziEJNDv9GPaIyduaedAJa7WjgFqFVD85I2xYlB1vXyydyre1J7zgO
          2mrA6Xq5LENwMv8U1i1c5WRcollVkpPJsPFrtteofMgasDq2FIy1obwKND2CkYhhzU5Vq
          UEa8hc2pyKBO9x3ekAmxJsDF1S6GplTCekukdEk8If7WemW84TF+EVFTB+zG/X9Nop37q
          uKSdhULmfmX4KLjjllvvFW2+9nCZyCOq7mC9j9UzW3f27zUc2ak+MJrjJeFdEuytXNBzs
          f+Xt/EWdoVamfRBlLVg7ugaoapJy3NFwpeJQULg4gLajFbywuqepfxdZD0NPU8+W6wEPo
          AmZFgBx4h/UHn4tM+VUroK5SORJgU7DxF6KNO9lesZvci2dqGCbobMWnNXi6gf7YK8vti
          v7a1yqQZMXYBaB1H34+TGS6loIJ0DFXCVnwffsyK9c+4vV41zGohIzBc/WUpuI=
        - nr6Ni4tauc3bqoGHOchQsR25l4RncWwGQiNQ/vcslas4LRHrcb590fh5fIurrNYS25bp7
          Di281F0gRMs8uWjrMQmU07TZVc1f8jgu+LY5XvUtouWyEBiMDBTRS4tsLOvz97MUigQsX
          ved8p9XXBEIDaLLZieR6pH5uQ7B2NyL9xPsTmmPBVeZn1TqVw1jognqiq/Va1YyZmWUAR
          9FJjcYv1mA1tZuAbpTOkO5IB1lNHSEpUOvou6bs0NL5dL2ilNx5Hx/rWz5D7zDsASpJ4Q
          aaZUdkCOoBNHXBOrZQ+7Dpf3PvE3k41kO3tvr0NunEQYwuvCpy9V2P6KI6yyFt2C4h1IN
          HHsOhi9zk8Y7pvAbhmmxF4o/ORgVx/Y4mNTuOjbth/J6G58U6+pX8xMvKLm6lcsIL8CXl
          x4mtP/6juvrnDzBS9xYPanrEzXTDJZQupQqBVd8TwetQv65jlyjwbB21L+gcYT0HUq8aI
          C0jFHAQ4mrNAJCOEqiDVWyS7v6f04WnZF8cBXlFjYZrlyZZx2Nymi+U5qv7UYFuUkrqXL
          wjp1nXYTWkxVsRFwaTr1x9E7GFCATr076oEELtGNno+uuy6C6C/UJLTzzLZSiBegJwSmH
          C5Urlgpc7enSu2s+Jp3lfuy1YDdCobkj1V6WtWC5pcCIXRiiRxDsq4xx358SdY=
        - XsyXZb/NVIEhOD4Rg3W6itdaUur/KlrYRm2DklW3FSLWYyQyAcRDJeAgKn4tHj/2Xn1D4
          q5i3yr4LFl8BcaWmJ8kxJ7w9/2ruRAmry6Z1gdlIapSLK7l3INs1jb2bCQTK9O5mRMkvH
          jRCuHt4P/9rx1WJoCZ0xRkqoXQLZ187PzDjGdcTYedx9mBodVtQWSBPcJbT67J3PaAxVE
          +xrIjMvKPiuVoUfoGU70OBmC7ypPpXD2cmiRUTHkIvY//L3opgFKaYTtbI9IdaugB5ZmG
          Zii+LFv8d5ftmSKhW5iD3iyGsfPL4PIyyn33SEWieduiRmmdgoxOtLaxu8tLgIyWk39ix
          MTw2AbOT7i/nHwAOs5GSKJhhIpDKyQvhL4DZZvx0NbmGHo4qsH9ozW49T3uPeGP7pnTKr
          wRpIw9Q8AqxpOzPiRi5aLB9KMWDMRb3MS1PgQdMZGeVV2sCMPkBMQemjh9PteCTzm3cIy
          +z8vhABU57UeCC1cvkN/bCDr/YCE8YZMpELRyy0SF0JjjAoTuECzFCJ+7Ye74QOhUUbkI
          /AZZEWtbPLv4oNlrnt0LPNi8PwxaSKjbxcoh44vdRarRJmKQ4HZ4k7R/e2wYqJ6PHu9a3
          yTjXdZu9yIh9trvwGX1mm7ykl/R2RhwUb1ym9r4VrmchJYjJEZBTBn7kzaxaps=
        - bM4LEfMZwqfJP62EcpcMRJFWs4feu7q5Y3SIFVQvo5zldLGoh+7htSOTLz8tmkBPTYLkH
          5kwoWVDn8fV4XHb7LcypL23yddRxJRF95l4yfi+Ntw/1y0+yCUvoHB1T+0+yvFm0+W4fX
          A/pqEEWaDcYego+LOMOgVe4bYG4aSY0AV6txjUfqIZLrHKbyYAS5w1cqM255EAH8PMT4m
          p2ukvyLlICD1/JO2Bcss4ZqlGaHjLxXTKYFt+6498cnxyYXXIQlQaK6Rn+tUn16JYRANn
          5F7gzB8RcIP95cqgzqjXJ0pYE+AnskSbatYO7gxg651ISs/jcMav+y1OOJAn1U0Bb3p5D
          ZgORArtbKFBbcEYgghOCaFWqRUvmswaqTULv6hjQd3aXci35YZ7xlWULc89M2LvPNj60Y
          r6klzieIcyt0HTslw2oY0MDXTCiBmBufX1DCGvbBUjEmi4Up/4c0zsyubxd5R/VfRMPaJ
          AIfuQJ20tzRR/BpPOevqCAZzP0rxhudlvOYK7+zWRe5DDJYi7e0lSU5y+BTV8UnLRliel
          Zs6jb9TUkd+SMQMUMrVMjtATe43TdIGSAfla3FxKsLAQH/Ngadq5pD/JQlMkofmeqCYOQ
          OUmM9AiFPXoHpRF164DoS+83q5QijxhI2DVaDP524uiRiFwjMaVNToirRudnGw=
