rabbitmq-server-config

# centos-release-config
centos-release-config
dhcp-config
dnsmasq-config
haproxy-config
initscripts-config
lighttpd-config
openssh-config
setup-config
systemd-config
audit-config
docker-config
containerd-config
multus-config
tuned-config
dmesg-config

# io-scheduler
io-scheduler
iptables-config
memcached-custom
ntp-config
pam-config
rsync-config
shadow-utils-config
sudo-config
syslog-ng-config

# util-linux-config
util-linux-config

# filesystem-scripts
filesystem-scripts

# iscsi-initiator-utils-config
iscsi-initiator-utils-config
nfs-utils-config
openldap-config
logrotate-config

# openvswitch-config
openvswitch-config

#python-siteconfig
python-siteconfig
