# List of packages to be included/installed in ISO

#audit-config
audit-config

# base-files-config
base-files-config

#containerd-config
containerd-config

#debian-release-config
debian-release-config

#dhcp-config
dhcp-config

#dnsmasq-config
dnsmasq-config

#docker-config
docker-config

#filesystem-scripts
filesystem-scripts

#initscripts-config
initscripts-config

#io-scheduler
io-scheduler

#iptables-config
iptables-config

#iscsi-initiator-utils-config
iscsi-initiator-utils-config

# lvm2-config
lvm2-config

#logrotate-config
logrotate-config

#lighttpd-config
lighttpd-config

#memcached-custom
memcached-custom

#multipath-config
multipath-config

#multus-config
multus-config

#nfs-utils-config
nfs-utils-config

#ntp-config
ntp-config

#openldap-config
openldap-config

#openssh-config
openssh-config

#pam-config
pam-config

#python-siteconfig
python-siteconfig

#rabbitmq-server-config
rabbitmq-server-config

#rsync-config
rsync-config

#sudo-config
sudo-config

#syslog-ng-config
syslog-ng-config

#systemd-config
systemd-config

#tuned
tuned-config
