#!/bin/sh

set -e

cp /usr/share/starlingx/default.ntpsec /etc/default/ntpsec
cp /usr/share/starlingx/ntp.conf /etc/ntpsec/ntp.conf

chmod 644 /etc/default/ntpsec
chmod 644 /etc/ntpsec/ntp.conf

#DEBHELPER#
