#!/bin/sh

set -e

cp /usr/share/starlingx/ntp.conf /etc/ntpsec/ntp.conf
cp /usr/share/starlingx/ntpd.sysconfig /etc/default/ntp

chmod 644 /etc/ntpsec/ntp.conf
chmod 644 /etc/default/ntp

#DEBHELPER#
