#!/bin/sh

set -e

cp -f /usr/share/starlingx/ssh_config /etc/ssh/ssh_config
cp -f /usr/share/starlingx/sshd_config /etc/ssh/sshd_config
cp -f /usr/share/starlingx/sshd.service /lib/systemd/system/sshd.service

#DEBHELPER#
